# Configuration for Rubocop

AllCops:
  Include:
    - Rakefile
    - providers/**/*.rb

# "hash_rockets" style can be changed to "ruby19" when Ruby 1.8.7 is no longer
# supported
HashSyntax:
  EnforcedStyle: hash_rockets

# This line can be removed once rubocop-todo.yml has been dispatched with
inherit_from: rubocop-todo.yml
